### PR TITLE
Style borders and background colors

### PR DESCRIPTION
**Pull request by aidando73**
Some basic quality of life styling enhancements. E.g. less harsher borders, less competing colours. Just wanted to draft these styling changes by you before I go on to the entire spreadsheet. Changes are currently only on "Architecture". If you're happy with them I can apply them to the entire spreadsheet.
Before:
Capture2

After:
Capture

### CODE REVIEW

**Comment by shenril** [comment]
Looks awesome ! Thanks for the work, let's apply on the whole spreadsheet !

**Comment by aidando73** [comment]
Oh haha didn't expect you to reply so quick. I was also tinkering with some colour palettes off of Refactoring UI. This one uses a Blue grey. You might like it better?
With blue grey

**Comment by shenril** [comment]
Indeed looks sweeter on the eye :)

**Comment by aidando73** [comment]
Ok all done. If you could have a quick look that would be great :)

**Comment by shenril** [comment]
Currently travelling but will merge that tonight ;) thanks for the work !

**Pull request merged**
